---
# SPDX-FileCopyrightText: 2026 Matthias Sitte
#
# SPDX-License-Identifier: MIT

- name: Validate sudoers configuration
  become: true
  ansible.builtin.command:
    cmd: "{{ _sudo__visudo_binary }} -c"
  changed_when: false
  tags:
    - sudo
    - sudo_validate
