---
# SPDX-FileCopyrightText: 2026 Matthias Sitte
#
# SPDX-License-Identifier: MIT

- name: Uninstall sudo packages
  ansible.builtin.import_tasks:
    file: uninstall_package.yml
  when: sudo__manage_package | bool
  tags:
    - sudo
    - sudo_uninstall
